config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
   
  root 'pages#home'
  get 'items/:id/products' => 'products#index'

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/categories' => 'items#index'

  get '/items/:id/pros' => 'pros#index'

  get '/suppliers' => 'suppliers#index', as: 'suppliers'

  get '/payment' => 'pages#payment'

 
  get '/carts' => 'carts#index'
  get 'carts/clear' => 'carts#clearCart'
  get '/carts/:id' => 'carts#add'

  get '/cart' => 'cart#index'
  get 'cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :items, :only => [:index, :show] do 
    resources :products, :only => [:show, :index] 
  end

  resources :products do 
    resources :comments
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	 has_many :products


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :products


end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :item
	belongs_to :cart
	has_many :comments

	has_attached_file :image, styles: {  medium: "170x150#", small: "160x160>", thumb: "60x60#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
   	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def add

	id = params[:id]
	if session[:cart] then
		cart = session[:cart]
	else
	session[:cart] = {}
	cart = session[:cart]
  end
	if cart[id] then
		cart[id] = cart[id] + 1
	else
		cart[id] = 1
  end
	redirect_to :action => :index

 
 end
 
 
 def clearCart
  session[:cart] = nil
  redirect_to :action => :index
 end
 
 def index
  if session[:cart] then
   @cart = session[:cart]
  else
   @cart = {}
  end

 end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
def create
	@product = Product.find(params[:product_id])
	@comment = Comment.create(params[:comment].permit(:content))
	@comment.user_id = current_user.id
	@comment.product_id = @product.id

	if @comment.save
		redirect_to root_path
	else
	render 'new'
	end
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	def index
		@items = Item.all
	
	end
	
	def show 
		@item = Item.find(params[:id])
		@product = @item.products
		
	end
	
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	
	def contact
	end
	def payment
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def show 
		@product = Product.find(params[:id])
		@comments = Comment.where(product_id: @product)
    

	end

	

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
def index
	
	@supply = Supplier.all
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/carts/index.html.erb
<h1>Carts#Index</h1>

app/views/comments/_form.html.erb
<%= form_for([@product,@product.comments.build]) do |f|%>
<strong><%= f.label :Reveiw %></strong><br>
<p><%= f.text_area :content %></p><br>
<%= f.submit :class => "btn btn-success"%>
<%end%>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Shop Homepage - Start Bootstrap Template</title>
<!-- Bootstrap Core CSS -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="css/shop-homepage.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<style>
 #gallery {
   margin:0;
   padding:0;
   list-style:none;

 }

 body {
    background-image: url("/assets/background.jpg");
    background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    background-attachment: fixed;
}

 #gallery li {

 	float:left;
 	width:25%;
 	margin:2.5%;
 	background-color: #f5f5f5;
 	color:#bdc3c7;
 	font-size: 1.75em;
 }
</style>

<body>
 <section id="gallery">
 	<% @items.each do |item|%>
 	<ul >
     <li><strong><%= link_to item.name,item_path(item)%></strong>
     	</li>
     </ul>
     <%end%>
   </section>


 <script src="js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/items/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Shop Homepage - Start Bootstrap Template</title>
<!-- Bootstrap Core CSS -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="css/shop-homepage.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<style>
 body {
    background-image: url("/assets/background.jpg");
    background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    background-attachment: fixed;
}

#gallery {
   margin:0;
   padding:0;
   

 }

 #gallery li {

 	float:left;
 	width:30%;
  height: 30%;
 	margin:0.5%;
 	color:#000;
 	font-size: 1.25em;
  list-style: none;
 

 }
</style>
<body>
 
<section id="gallery">
<% @product.each do |p|%>
<ul>
	<li><div><%= image_tag p.image.url(:medium)%></div>
	<div><strong><%= p.name%></strong>
	<p>Price:<%=number_to_currency(p.price)%><br>
	<%= link_to "Learn More", item_product_path(p.Item_id, p), :class => "btn btn-danger" %></p></div></li></ul>

<%end%></section>

 <script src="js/jquery.js"></s
cript>
<!-- Bootstrap Core JavaScript-->
<script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/products/index.html.erb
<% @products.each do |product|%>
	<%= image_tag product.image%>
	<%= product.price%>
	<%= product.name%>
	<%end%>

app/views/products/show.html.erb
<style>
.container {
background-color: #f5f5f5;
}
</style>
<body>
<div class="container">
<%= image_tag @product.image%><br>
<strong><%= @product.name%></strong><br>
<h3>Price:<%=number_to_currency(@product.price) %></h3><br>
<%= @product.description%><br>
<a href="/carts/<%=@product.id%>" class= "btn btn-danger">AddToCart</a>
 
<a href ="/suppliers", class= "btn btn-danger">Suppliers</a>
<a href ="/payment", class= "btn btn-success">Buy Now</a><br>
<p><h2><%=pluralize(@product.comments.count, "Reviews")%></h2></p><br>
<% @comments.each do |comment|%>

<h4><strong><%= comment.user.email%></strong></h4>
<p><%= comment.content%></p>
<%end%>
<p><%= render 'comments/form'%></p>
</div></body>

app/views/suppliers/index.html.erb
<% @supply.each do |sup|%>
<div class="jumbotron">
	<h3>
<%= sup.company_name%></h3>
<h5><%= sup.contact_fname%>
<%= sup.contact_lname%>,
<%= sup.city%></h5>
<p><%= sup.state%>, 
<%= sup.country%>.<br>
Email:<%= sup.email%><br>
Phone:<%= sup.phone_no%></p>
</div><%end%>